### ISSUE TITLE
Create a Dockerfile for this app

### ISSUE THREAD

**Issue by steveyken** [crossroads/socket.io-webservice#33]
This app would benefit from running in a docker container.

For the docker base image, use docker tag `node:lts-alpine3.14` from https://hub.docker.com/layers/node/library/node/lts-alpine3.14/images/sha256-9acf37f13f64be151771b81b987ff7343b2876040e052b16f177627657ce432c?context=explore

**Comment by saschanockel** [comment]
Hey, I would like to take on this issue for a Hacktoberfest contribution.

**Comment by steveyken** [comment]
Thank you Sascha, I'd very much appreciate it

**Comment by steveyken** [comment]
Thank you for this work, I've reviewed and merged the PR and tagging this ticket as hackoberfest-accepted to ensure you receive the credits.

**Comment by saschanockel** [comment]
Thank you very much :), you missed the t in hacktober ^^

**Comment by steveyken** [comment]
Doh! Thanks for spotting. Fixed tag
